### ISSUE TITLE
big man ting yea 

### ISSUE THREAD

**Issue by unknwnkam** [R14Z/portofolio#1]
ye so basically you are so cool and i think that u will make it in life because u have the abilitys and everything and i also see as a professional coder that u know how to eat the < and stuff like that which is really impressive as ive never seen anyone else do that so the only issue is the hair that give ur code the line cos its very messed up and squiggly meaning it should have some work done to it anyways thas enough from me and be a good boy c:

**Comment by R14Z** [comment]
ofc
